### ISSUE TITLE
Got Rejected by 15 out of 17 companies 

### ISSUE THREAD

**Issue by SkyTreasure** [jkup/rejected.us#15]
Out of 17 companies 15 rejected me and I rejected 1 out of 2 :P in a period of 1 month

**Comment by jkup** [comment]
Wow.. that's a busy month! Do you have a Twitter account you'd like me to link to your story? Or use Github?

**Comment by SkyTreasure** [comment]
Yea one of the busiest and tougest month

**Comment by SkyTreasure** [comment]
Yea one of the busiest and tougest month. Getting up after failing and going to another interview was so difficult. But I learnt a lot in that 30days :) . I have twitter account this is my I'd -@SkyTreasure
