### ISSUE TITLE
rejected from several companies

### ISSUE THREAD

**Issue by r5liang** [jkup/rejected.us#16]
UCSD student: rejected without interview from all but 5 out of 80+ internship applications and finally received offer from Google

**Comment by r5liang** [comment]
sorry accidentally posted this before i was ready

**Comment by jkup** [comment]
Wow what a journey! Do you have a Twitter account you'd like me to link to? Or should I use Github?

**Comment by r5liang** [comment]
Nah I don't have a Twitter

**Comment by jkup** [comment]
Any chance you have a profile picture I can use? :) Trying to keep a consistent theme

**Comment by r5liang** [comment]
idk I'm not sure I'd be comfortable putting them here yet, but it's okay to exclude me

**Comment by jkup** [comment]
Ok perfect. I'm going to close this issue for now as I'm looking for full name and images but if you ever want to go public with it please just let me know! Thanks for sharing!
