### ISSUE TITLE
Rejected at more than 20 places before landing a gig at Microsoft

### ISSUE THREAD

**Issue by sebastianbk** [jkup/rejected.us#18]
While finishing up my master's degree I was sending out tons of applications to big corps for software development jobs but I was rejected by virtually all of them. One week I was rejected by two companies I really wanted to work for so I was sad and got drunk in the weekend. The following Monday I had an offer from Microsoft sitting in my inbox.

**Comment by jkup** [comment]
Thanks for adding your story!
