### ISSUE TITLE
Linode

### ISSUE THREAD

**Issue by salcedo** [jkup/rejected.us#19]
Got rejected by Linode because I'm a convicted hacker. Shortly thereafter, I won $50 Linode credit and a Raspberry Pi 2 through a Linode-sponsored challenge on True Ability. They probably think I hacked that too.

**Comment by jkup** [comment]
Woah!  Do you by chance have a Twitter account I can link your story to? Otherwise I can use your Github :)

**Comment by salcedo** [comment]
Not on Twitter. Please use my Github.

**Comment by jkup** [comment]
Awesome. Added.
