### ISSUE TITLE
@sebmck

### ISSUE THREAD

**Issue by sebmck** [jkup/rejected.us#23]
Got rejected from a junior position at Atlassian for not knowing enough about JavaScript. Shortly after they now use the JavaScript compiler that I wrote across most of their JavaScript stack. Now work for Facebook.

**Comment by dd1994** [comment]
cool :+1:

**Comment by jkup** [comment]
Wow... thanks for sharing! I'm a big Babel fan :D

**Comment by shaunlebron** [comment]
this is amazing
