### ISSUE TITLE
Add RSS support

### ISSUE THREAD

**Issue by HorstMumpitz** [jkup/rejected.us#25]
Hi, 

what a lovely idea which encourages me a lot. 

I really would appreciate if the site could support RSS. Receiving the newest entries via a feedreader of your choice has the huge advantage that you never miss the latest submissions. 

Thank you for your efforts, 
Dennis.

**Comment by jkup** [comment]
That would be awesome! If anyone is up for helping I'd love that. Otherwise I'll take a look in a bit :)

**Comment by HorstMumpitz** [comment]
I see two different possibilities: 

1. Generating offline a feed file after a new entry was added e.g. with the help of a grunt task.

2. Adding a new endpoint like '/feed.xml' which generates the feed dynamically. 

Each solution requires that the feed is linked within the markup. 

Which way would you prefer?

**Comment by jkup** [comment]
I kind of like the idea of adding a new /feed.xml endpoint if you're indifferent! :)

**Comment by HorstMumpitz** [comment]
I agree. This solution avoids adding extra processes and dependencies like Grunt or Gulp. If you don't mind I would try to implement a solution at the weekend.

**Comment by jkup** [comment]
Perfect!!

**Comment by HorstMumpitz** [comment]
Before opening a Pull Request I'd like to link to my commit. 

[Add RSS support](https://github.com/HorstMumpitz/rejected.us/commit/480618a6aed31aab6c7d1e008cb97b7de23c6163)

Some notes about my the implementation: 
* The project uses react for rendering the view. Actually a feed is nothing else then a different view on the data but the RSS creation is located in server,js. The reason: views/ seems to be reserved for react as defined in: app.set('views', __dirname + '/views');
* I added a function readData which returns the data.json and is used in both endpoints.

If you're ok with the commit I can open a PR.

Best regards, 
Dennis.

**Comment by jkup** [comment]
This looks great to me! The one thing I see is that when I try to validate the feed using https://validator.w3.org/feed/check.cgi we're getting an error about re-using the same guid. I think this is because the guid defaults to the url and these stories don't have individual urls. But I think that's a bigger project so I think this is a great addition!

**Comment by HorstMumpitz** [comment]
Hey,

sorry for the late reply. Christmas is coming and things have to be organized. 

You're right with the guid. At the moment it is not possible to link to a single rejection that's why there is a "global" guid. 

Thank you for your review. I'll open a PR in the next minutes.
