### ISSUE TITLE
Rejected by GitHub

### ISSUE THREAD

**Issue by stevenhauser** [jkup/rejected.us#26]
Hey, great website idea. It's nice to know that even top-notch devs get rejected. Here's my story:

Rejected by GitHub for a frontend developer opening because my HTML, CSS, and JS skills were strong, but I failed to demonstrate my…Ruby skills—which weren't even asked about. Ya know, frontend stuff.

But hey, hiring is hard.

**Comment by jkup** [comment]
Thanks for submitting! Adding now.
