### ISSUE TITLE
Rejected by Amazon

### ISSUE THREAD

**Issue by rcorrear** [jkup/rejected.us#29]
After applying for a Senior Development Engineer position in the Dublin office I get an email from HR for the Senior Cloud Support Engineer position. After two (technical) phone interviews and an 8 hour on-site multi team interview I get back the results: You really did very well in the interviews, but we're not extending an offer because you are a better fit for our Senior Development Engineer position!!

**Comment by jkup** [comment]
Wow.. thanks! Added.
