### ISSUE TITLE
Rejected by many companies. Now work at blackberry

### ISSUE THREAD

**Issue by rajat-arora** [jkup/rejected.us#30]
Was rejected by many companies which one of them was AutoDesk whom escorted me out of their office midway through the interview for having more knowledge of java over C++.  I kept at it and now work at BlackBerry as my job. #StickWithIt

**Comment by jkup** [comment]
Great story! Do you by chance have a Twitter account I can link your story to? Otherwise I can use Github!

**Comment by rajat-arora** [comment]
https://twitter.com/rajatonit

**Comment by jkup** [comment]
Thank you! Just added. :)
