### ISSUE TITLE
Jonas orinovski, france

### ISSUE THREAD

**Issue by jokoon** [jkup/rejected.us#31]
I was rejected by ubisoft, bull/amesys, and dozen of other tech companies, because I don't have experience in java, .net, while I'm skilled in C/C++, python, linux. I went through many tests, including IQ (125) and programming tests.

Still unemployed. Have given up, but I still intend to make a tiny game, if I can find the motivation.

**Comment by jkup** [comment]
Thank you so much for sharing your story! Do you by chance have a Twitter account I can link it to? Otherwise I'll use your Github!

**Comment by jkup** [comment]
Added!

**Comment by jokoon** [comment]
you can add my github yes!
