### ISSUE TITLE
Use GitHub corners instead of the ugly default GitHub ribbons

### ISSUE THREAD

**Issue by minnix** [jkup/rejected.us#33]
[GitHub Corners](http://tholman.com/github-corners)

**Comment by jkup** [comment]
These are cool! I hadn't seen them before. I'll swap them out once traffic dies down :)

**Comment by gguillotte** [comment]
Please mind the ribbon/corner on mobile, too. It covers part of the heading text at the moment.

**Comment by jkup** [comment]
Yes, I noticed that too! Thanks

**Comment by jkup** [comment]
Added github corners and it seemed to fix the mobile issue so... :)
