### ISSUE TITLE
Rejected by the entire East Coast! Now at IBM

### ISSUE THREAD

**Issue by rachelnicole** [jkup/rejected.us#34]
When I graduated from a less than desirable college, no employers in New York would take me seriously... so I moved to St. Louis. Everyone in the midwest didn't care where I went to school, and instead I was highly in demand as a developer with a design background. I worked in agencies for 3 years, until I got a job offer from Adobe and moved back to NYC. Now I'm at IBM Watson, and it's the best.

I'm @ohhoe on twitter, since I saw you're linking that, and my name is Rachel White.

**Comment by jkup** [comment]
Awesome story! And thanks for making it easy for me re: twitter handle and full name!!
