### ISSUE TITLE
Rejected by multiple universities and now Google, Microsoft and Amazon

### ISSUE THREAD

**Issue by aditya1** [jkup/rejected.us#36]
I'm originally from India. I have been rejected by 10-15 universities before landing in Virginia Tech. It took me 3 years to get my first admit. During my grad school I have been rejected by Google for not knowing their book search algorithm :-). Rejected by Microsoft for whatever reason and I blew up Amazon interview. Now work at  European company in New England. Still eager to go to Silicon Valley, maybe 2016 is my year.

**Comment by jkup** [comment]
I think it'll definitely be your year!! Do you by chance have a Twitter account I can link it to? Otherwise I'll use your Github!

**Comment by aditya1** [comment]
I do not have Twitter account. Sorry!

**Comment by jkup** [comment]
What about a profile picture? :) Just trying to keep the design consistent!

**Comment by jkup** [comment]
Added!
