### ISSUE TITLE
Rejected by Harvard Business School, Airbnb and Google

### ISSUE THREAD

**Issue by jasonshen** [jkup/rejected.us#37]
Applied to the Harvard Business School as a Stanford honors grad with a 740 GMAT, no interview. Was rejected from Airbnb for a customer support role and later was passed over for a PM role at Google after 2 phone screens.

I've cofounded Y Combinator startup (Ridejoy YC S11) and was selected by the White House to serve as a Presidential Innovation Fellow. Today I'm a product manager at Etsy. Timing and fit are everything.

**Comment by jkup** [comment]
Awesome story, thanks for adding!

**Comment by jasonshen** [comment]
Thanks! Note, I had a small typo and needed to add an "a" between cofounded and Y Combinator

**Comment by jasonshen** [comment]
Also my twitter is @jasonshen!
