### ISSUE TITLE
Rejected by Apple 4 times while employed at Harvard

### ISSUE THREAD

**Issue by notasausage** [jkup/rejected.us#40]
Apple interviewed me 4 times for 3 positions, all while I was employed at Harvard University. I even had to talk through designing the "iStove" for Steve Jobs and explain how Google Maps worked using a whiteboard. They never hired me and I left Harvard to work for myself a year later.

Patrick Haney, @notasausage

**Comment by jkup** [comment]
Great story! Thanks so much for sharing it!
