### ISSUE TITLE
Rejected at every Jr Level - Entry Level position

### ISSUE THREAD

**Issue by pjoesphs** [jkup/rejected.us#41]
Since 2013  and after graduating with honors  for the 2nd time from college, 1st time in IT 2nd time in Graphic Design.  I've applied at 100's of companies for  Jr and Entry level positions. I've received  every excuse under the sun of why I am not qualified or not being called in for an interview. Mostly the good old cookie cutter  response of " We went with another candidate... good luck!"  
Yes, I have been  offered LOW unsustainable wages to start off with, One of which I accepted only for the company to renegotiate and tell me that they gave the job to someone else 3 days after I accepted. 
I've had a few bizarre interviews also. One interview for example the person interviewing me sat there telling me about his personal life ( divorce, young child, where he used to work, what his favorite activities are... ect.. )  I've been  offered retail jobs with no benefits,  I've been told to go work in fast food, and  at places like Wal Mart.  This is b***s**t !!  Life is not supposed to be like this!  Rejections Suck!  #16

**Comment by jkup** [comment]
Thank you for adding your story! Could I have a full name and profile image to add to the site?

**Comment by jkup** [comment]
Please re-open if you want to share your full name and profile!! Just trying to clean through older submissions and I need a picture to put them on the site.
