### ISSUE TITLE
Rejected by Sucuri, Buffer, and Road Runner

### ISSUE THREAD

**Issue by rwilki** [jkup/rejected.us#42]
I submitted applications to Sucuri, Buffer, and Road Runner Sports in hopes of furthering my career as a web and graphic designer. Ultimately, my career path has evolved just fine as I'm busier now more than ever working for myself. I'm challenged, rewarded, and love what I do. If I could manage the stress, it would be all good.

**Comment by jkup** [comment]
Could I get a full name to add to the site? Thanks so much for sharing!

**Comment by rwilki** [comment]
Sure. Robert Wilkins.

Thanks, what an excellent concept you came up with!

On Dec 17, 2015, at 5:20 AM, Jon Kuperman <notifications@github.com> wrote:

> Could I get a full name to add to the site? Thanks so much for sharing!
> 
> —
> Reply to this email directly or view it on GitHub.
> 





	+++
	Robert Wilkins • Director
	www.commtechnologies.com
	bwilkins@commtechnologies.com  • 410-861-8274
	Communication Technologies, LLC
	Follow me on Twitter
	Add me (Google+) to your Circles

**Comment by jkup** [comment]
Thank you! Added yours :)

**Comment by rwilki** [comment]
Thank you. Have a great day!

Bob

On Dec 17, 2015, at 2:35 PM, Jon Kuperman <notifications@github.com> wrote:

> Thank you! Added yours :)
> 
> —
> Reply to this email directly or view it on GitHub.
> 





	+++
	Robert Wilkins • Director
	www.commtechnologies.com
	bwilkins@commtechnologies.com  • 410-861-8274
	Communication Technologies, LLC
	Follow me on Twitter
	Add me (Google+) to your Circles
