### ISSUE TITLE
Rejected By Netflix

### ISSUE THREAD

**Issue by derickbailey** [jkup/rejected.us#45]
I was told by a hiring manager at Netflix that my career would be over if I wasn't willing to relocate my family to San Francisco. Since then, I've had 2 full time jobs that were 100% remote (work from home), have been a full time consultant with clients around the world (Germany, Japan, Denmark, South America, Canada, and all over the U.S.) Now, I'm an entrepreneur as well as consultant, I work less hours than any full time job I've ever had, and I earn more than ever.

**Comment by benoror** [comment]
+1 Nice! Any tips or advice for a potential career as web developer consultant/freelancer?

**Comment by derickbailey** [comment]
probably the best is double your rate. then double it again. keep doubling it until people consistently say no. seriously. i went from $50/hr to $250/hr in less than a year.

also, charge by the day or week, not by the hour. don't say a specific # of hours in a week, either. just say per week, and then provide enough value in that week to justify your price :)

**Comment by jimholmes** [comment]
Plus you make your own bacon. That's worth all the changes, period. :)

Something I've found useful is to create package offerings. This has generally been around assessments I'm doing for companies, but the idea carries for other kinds of work. I'll charge $10,000 for five days of work which rolls out to initial collaboration, three days on site (T&E extra), then creating a report and debrief of what I found. They get an action plan with items that can roll on to their backlog for addressing any findings.

Tip: Do ***NOT*** compromise on the price as a loss-leader for future work. This sort of assessment/consultation **is** your expertise.

IAC, it's obvious you're killing it without Netflix. I have good pals there, but would never, ever consider living in the Bay Area.

**Comment by braidn** [comment]
Absolutely :+1: to the charge by the week

**Comment by jkup** [comment]
Awesome contribution! Also awesome advice!!

**Comment by benoror** [comment]
@derickbailey @jimholmes @jkup Thanks! :smile:

**Comment by anthonybrown** [comment]
@derickbailey so awesome :+1:
