### ISSUE TITLE
Rey Bango @reybango (Microsoft)

### ISSUE THREAD

**Issue by reybango** [jkup/rejected.us#49]
I was rejected by Arthur Andersen Consulting in the '90s because I didn't have an undergraduate degree and also by a number of well-known Silicon Valley companies because I couldn't relocate. Since then I've worked at great companies like Mozilla, Telerik & Microsoft, all remotely and with no undergrad degree.

**Comment by jkup** [comment]
Added, thanks so much for sharing!
