### ISSUE TITLE
Rejected by NFL

### ISSUE THREAD

**Issue by ajpiano** [jkup/rejected.us#58]
I wanted to be a [professional football player](http://ajpiano.com/i-would-like-to-be-a-quarterback-or-wide-receiver/) but the New York Jets didn't want me because I couldn't run a sub-4.3 second 40 yard dash. Now I am Director of Community at Bocoup so I like to think I landed on my feet.

![](http://ajpiano.com/repeatingfirstgrade/16oct1992_qb_or_wr_low.jpg)

**Comment by jkup** [comment]
The saddest story of them all :(

**Comment by rachelnicole** [comment]
:+1:

**Comment by jkup** [comment]
Thanks so much for adding :)
