### ISSUE TITLE
Why do you need a server?

### ISSUE THREAD

**Issue by tytskiy** [jkup/rejected.us#60]
I don't get why do you need a server for such web-site?
Everything of current functionality can be done by pure frontend side.

**Comment by jkup** [comment]
Yeah there really isn't a reason.. Want to submit a PR? Otherwise I'll refactor it tonight :)

**Comment by RobinsonKameron** [comment]
Well first off he is using a express for node and Xjs for tempting. Let's say if the project were to have users instead submit stories, they could automatically send to a database.

In my opinion It's defiantly better to use a framework with the idea in mind that your content may not forever be static. Even for a small app, it's smart to start off with a scalable application design in mind.

**Comment by phanimahesh** [comment]
Well, it is also possible to start with a frontend-only app and add a separate backend when needed.

Also, to be considered: When this grows, it would not be feasible to show all of the entries on a single page. And maintaining that large single json file might prove difficult. Why not have one file per person?

**Comment by tytskiy** [comment]
> Yeah there really isn't a reason.. Want to submit a PR? Otherwise I'll refactor it tonight :)

No-no, it was just a question. Because i think it would be less time of initial development if you did all by static frontend. There is no reason to spend time on redo everything.

@jkup, i am not sure if it's correct place for discussion - but now you have a server and non existent request just shows default 404 page. Will you accept PR with redirect 404 to Homepage?

**Comment by tytskiy** [comment]
as there is no discussion i close the issue
