### ISSUE TITLE
Mozilla

### ISSUE THREAD

**Issue by creationix** [jkup/rejected.us#7]
I applied to work at Mozilla on FirefoxOS.  They said my C++ wasn't good enough. My day job at Rackspace is mostly C code with some Lua and JS (https://luvit.io/).

**Comment by creationix** [comment]
To be fair, C++ is not C, I still stink at C++.

But FirefoxOS involves a ton of JS, HTML, and CSS where I had over a decade of professional experience.

**Comment by TheAlphaNerd** [comment]
all I can think about is LOL

**Comment by jkup** [comment]
Wow.. I also applied there! ( but never heard back ) Thanks for sharing.. huge fan of nvm btw :)

https://twitter.com/jkup/status/676585971404664832
