### ISSUE TITLE
Rejected by dad

### ISSUE THREAD

**Issue by thejameskyle** [jkup/rejected.us#72]
I'm not sure if this is appropriate for this project, but I felt compelled to share.
Feel free to... *reject* this.

---

I always had a poor relationship with my father. Before we stopped talking, he said lots of terrible things to me. He said that I had no future. Three years later, at 21 years old, I had already experienced a ton of professional success. I was making a six figure salary at 20 and traveling around the world to speak at 21. Even better– I've been able to help pay for my mom to finish her masters degree. Fuck you Eric, I'm the shit.

**Comment by jaronoff** [comment]
+1

**Comment by SayBeano** [comment]
++1

**Comment by samccone** [comment]
+1

**Comment by jkup** [comment]
Thank you so much for this! Added.
