### ISSUE TITLE
Rejected By Valve Software

### ISSUE THREAD

**Issue by erayarslan** [jkup/rejected.us#75]
Rejected by Valve Software for a Software Engineer position because i was young. (when i was 19)

**Comment by erayarslan** [comment]
Submitting this as a PR .

**Comment by jkup** [comment]
Thank you!! Falling behind on the issues :/

**Comment by jmar910** [comment]
Rejected by Valve as a web developer because I wasn't "senior enough". They drew this conclusion by just looking at my resume and didn't even give me an interview. 4 months later, I got a job as a senior web engineer at Heroku.
