### ISSUE TITLE
@kvz

### ISSUE THREAD

**Issue by kvz** [jkup/rejected.us#8]
I was phone-screened by Google late 2010. I was nervous and unhappy with my performance but they never shared honest feedback or gave me a chance to set things straight. Although to be honest, phone-screenings still terrify me and I doubt a second one would make me shine. I was sad but went on to focus on a captivating side-project which (through lucky events and hard work) turned into a great little company. I get to dedicate most of my time to open source and I can't imagine being happier with a job right now (yes even working at Google)

**Comment by jkup** [comment]
So awesome how it all worked out! Thanks for contributing!
