### ISSUE TITLE
Didn't make it past many phone screens but look at me now!

### ISSUE THREAD

**Issue by TheAlphaNerd** [jkup/rejected.us#9]
First time interviewing I didn't get past the phone screen at google, twitter, or a number of other places. A startup offered me a 10 week internship way below market rate. I held out and got a decent job at Famous Industries where I got a ton of excellent opportunities.

I was laid off just over a year later due to downsizing and started interviewing again. Didn't get through the phone screen of a major online retailer... although their interview process left a lot to desire.

In the end I had two offers and was at the final interview stage at three other organizations before deciding to go to IBM to work as a node collaborator.

It turns out a year in the field can make a huge difference.

**Comment by jkup** [comment]
That's so awesome!
